In [16]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import defaultdict
from Bio import SeqIO

In [17]:
dataset_home = "~/Desktop/datasets"
datatasets = {
    "hiv": f"{dataset_home}/original/hiv/data_clean",
    "sars_kevolve": f"{dataset_home}/original/sars_cov2/data_clean",
    "denv_gramep": f"{dataset_home}/original/denv/data_clean",
    "hbv": f"{dataset_home}/original/HBV/data_clean",
    "mkpx": f"{dataset_home}/original/mkpx/data_clean",
    "sars_ncbi": f"{dataset_home}/new_sars_denv/denv_sars_cov_2/sars_ncbi_clean/test",
    "denv_ncbi": f"{dataset_home}/new_sars_denv/denv_sars_cov_2/denv_ncbi_clean/test",
}

In [18]:
rows = []
for name, path in datatasets.items():
    root = Path(path).expanduser()
    subs = [d for d in root.iterdir() if d.is_dir()]
    # datasets organised by class folder: ignore the train/test split copies;
    # the NCBI ones only have train/test, so there we merge both back together
    classdirs = [d for d in subs if d.name not in ("train", "test")] or subs

    by_class = defaultdict(list)
    for d in classdirs:
        for fasta in d.rglob("*.fasta"):
            by_class[fasta.stem] += [len(r.seq) for r in SeqIO.parse(fasta, "fasta")]

    for cls, seqs_len in sorted(by_class.items()):
        mean = np.mean(seqs_len)
        rows.append({
            "dataset": name,
            "class": cls,
            "n_seqs": len(seqs_len),
            "mean": mean,
            "sd": np.std(seqs_len),
            "variation": np.std(seqs_len) / mean,
            "min": min(seqs_len),
            "max": max(seqs_len),
        })

df = pd.DataFrame(rows)
df

,dataset,class,n_seqs,mean,sd,variation,min,max
0,hiv,HIV1_A,133,8878.300752,438.020976,0.049336,8009,9854
1,hiv,HIV1_B,128,9351.789062,441.392287,0.047199,8005,9915
2,hiv,HIV1_C,130,9148.084615,349.096108,0.038161,8134,9913
3,hiv,HIV1_D,86,8963.069767,386.529002,0.043125,8143,9839
4,hiv,HIV1_F,90,8944.622222,353.483131,0.039519,8096,9802
5,hiv,HIV1_G,94,9041.106383,363.940651,0.040254,8003,9792
6,sars_kevolve,Alpha,139506,29835.111544,55.618752,0.001864,29419,29904
7,sars_kevolve,Beta,647,29811.004637,57.532156,0.001930,29636,29903
8,sars_kevolve,Delta,8424,29801.185066,63.068428,0.002116,29402,29912
9,sars_kevolve,Epsilon,13649,29834.784013,62.382077,0.002091,29430,29912
10,sars_kevolve,Eta,664,29740.454819,70.955618,0.002386,29503,29888
11,sars_kevolve,Gamma,7401,29812.478584,62.394074,0.002093,29480,29912
12,sars_kevolve,Iota,17380,29803.793326,56.313759,0.001889,29556,29902
13,sars_kevolve,Kappa,121,29840.950413,51.769172,0.001735,29701,29902
14,sars_kevolve,Lambda,401,29794.019950,55.342863,0.001858,29568,29903
15,sars_kevolve,Omicron,88609,29764.840942,68.112023,0.002288,29375,29903
16,denv_gramep,type1,2408,10582.433140,195.009944,0.018428,10179,11195
17,denv_gramep,type2,1688,10645.745853,137.774022,0.012942,10176,10991
18,denv_gramep,type3,1223,10553.109567,201.217641,0.019067,10173,10810
19,denv_gramep,type4,449,10418.966592,226.283237,0.021718,10164,10772
20,hbv,A,768,3220.039062,5.304630,0.001647,3182,3233
21,hbv,B,1609,3214.904910,2.574973,0.000801,3185,3275
22,hbv,C,2559,3212.946073,6.400059,0.001992,3182,3254
23,hbv,D,1089,3182.388430,3.387805,0.001065,3182,3221
24,hbv,E,274,3211.113139,4.032483,0.001256,3182,3212
25,hbv,F,177,3214.593220,3.949334,0.001229,3182,3227
26,mkpx,I,818,196057.283619,1538.089712,0.007845,189200,206372
27,mkpx,II,2584,196938.379257,1519.857313,0.007717,180851,210919

In [19]:
rows = []
for name, path in datatasets.items():
    root = Path(path).expanduser()
    for fasta in sorted(root.rglob("*.fasta")):
        seqs_len = [len(r.seq) for r in SeqIO.parse(fasta, "fasta")]
        if not seqs_len:
            continue
        mean = np.mean(seqs_len)
        rows.append({
            "dataset": name,
            "file": str(fasta.relative_to(root)),
            "n_seqs": len(seqs_len),
            "mean": mean,
            "sd": np.std(seqs_len),
            "variation": np.std(seqs_len) / mean,
            "min": min(seqs_len),
            "max": max(seqs_len),
        })

df = pd.DataFrame(rows)
df

,dataset,file,n_seqs,mean,sd,variation,min,max
0,hiv,HIV1_A/HIV1_A.fasta,133,8878.300752,438.020976,0.049336,8009,9854
1,hiv,HIV1_B/HIV1_B.fasta,128,9351.789062,441.392287,0.047199,8005,9915
2,hiv,HIV1_C/HIV1_C.fasta,130,9148.084615,349.096108,0.038161,8134,9913
3,hiv,HIV1_D/HIV1_D.fasta,86,8963.069767,386.529002,0.043125,8143,9839
4,hiv,HIV1_F/HIV1_F.fasta,90,8944.622222,353.483131,0.039519,8096,9802
5,hiv,HIV1_G/HIV1_G.fasta,94,9041.106383,363.940651,0.040254,8003,9792
6,sars_kevolve,Alpha/Alpha.fasta,139506,29835.111544,55.618752,0.001864,29419,29904
7,sars_kevolve,Beta/Beta.fasta,647,29811.004637,57.532156,0.001930,29636,29903
8,sars_kevolve,Delta/Delta.fasta,8424,29801.185066,63.068428,0.002116,29402,29912
9,sars_kevolve,Epsilon/Epsilon.fasta,13649,29834.784013,62.382077,0.002091,29430,29912
10,sars_kevolve,Eta/Eta.fasta,664,29740.454819,70.955618,0.002386,29503,29888
11,sars_kevolve,Gamma/Gamma.fasta,7401,29812.478584,62.394074,0.002093,29480,29912
12,sars_kevolve,Iota/Iota.fasta,17380,29803.793326,56.313759,0.001889,29556,29902
13,sars_kevolve,Kappa/Kappa.fasta,121,29840.950413,51.769172,0.001735,29701,29902
14,sars_kevolve,Lambda/Lambda.fasta,401,29794.019950,55.342863,0.001858,29568,29903
15,sars_kevolve,Omicron/Omicron.fasta,88609,29764.840942,68.112023,0.002288,29375,29903
16,denv_gramep,type1/type1.fasta,2408,10582.433140,195.009944,0.018428,10179,11195
17,denv_gramep,type2/type2.fasta,1688,10645.745853,137.774022,0.012942,10176,10991
18,denv_gramep,type3/type3.fasta,1223,10553.109567,201.217641,0.019067,10173,10810
19,denv_gramep,type4/type4.fasta,449,10418.966592,226.283237,0.021718,10164,10772
20,hbv,A/A.fasta,768,3220.039062,5.304630,0.001647,3182,3233
21,hbv,B/B.fasta,1609,3214.904910,2.574973,0.000801,3185,3275
22,hbv,C/C.fasta,2559,3212.946073,6.400059,0.001992,3182,3254
23,hbv,D/D.fasta,1089,3182.388430,3.387805,0.001065,3182,3221
24,hbv,E/E.fasta,274,3211.113139,4.032483,0.001256,3182,3212
25,hbv,F/F.fasta,177,3214.593220,3.949334,0.001229,3182,3227
26,mkpx,I/I.fasta,818,196057.283619,1538.089712,0.007845,189200,206372
27,mkpx,II/II.fasta,2584,196938.379257,1519.857313,0.007717,180851,210919
28,sars_ncbi,Alpha.fasta,9339,29833.360852,74.568651,0.002500,28439,29905
29,sars_ncbi,Beta.fasta,388,29786.932990,49.498471,0.001662,29636,29885
30,sars_ncbi,Delta.fasta,9896,29871.501617,66.086591,0.002212,28551,29912
31,sars_ncbi,Epsilon.fasta,9401,29810.281991,81.058739,0.002719,28621,29904
32,sars_ncbi,Eta.fasta,422,29714.838863,66.279800,0.002231,29503,29888
33,sars_ncbi,Gamma.fasta,9557,29756.864183,136.837569,0.004599,28483,29911
34,sars_ncbi,Iota.fasta,8469,29746.840949,81.381446,0.002736,28627,29903
35,sars_ncbi,Kappa.fasta,70,29812.071429,44.004325,0.001476,29701,29902
36,sars_ncbi,Lambda.fasta,553,29777.110307,39.895802,0.001340,29653,29894
37,sars_ncbi,Omicron.fasta,1132,29771.563604,44.423719,0.001492,29540,30128
38,denv_ncbi,type1.fasta,4638,10514.736956,209.324615,0.019908,10168,11195
39,denv_ncbi,type2.fasta,4235,10512.683117,203.076261,0.019317,10168,10940
40,denv_ncbi,type3.fasta,2356,10512.208829,202.379094,0.019252,10168,10810
41,denv_ncbi,type4.fasta,697,10510.616930,155.539293,0.014798,10181,10772